#!/usr/bin/env bash
# Install the load balancer

apt-get -y install haproxy

# edit config file
server_config=\
"
frontend my_frontend
        bind *:80
        mode http
        default_backend my_backend_1
backend my_backend_1
        balance roundrobin
        server 540-web-01 35.196.96.41	 check
        server 540-web-02 3.234.218.189 check
"
 echo "$server_config" >> /etc/haproxy/haproxy.cfg

 echo "ENABLED=1" >> /etc/default/haproxy

 sudo service haproxy restart
