#!/usr/bin/env bash                                                             
# This script that accepts one argument whoami                                       
# It runs the 'whoami' command under the user passed as argument
sudo -u "$1" whoami
